export type SeedSource = {
  slug: string;
  name: string;
  siteUrl: string;
  rssUrl: string;
  authorityScore: number;
  tags: string[];
};

export const SEED_SOURCES: readonly SeedSource[] = [
  {
    slug: "cloudflare",
    name: "Cloudflare Blog",
    siteUrl: "https://blog.cloudflare.com",
    rssUrl: "https://blog.cloudflare.com/rss/",
    authorityScore: 0.95,
    tags: ["cloudflare", "networking", "performance", "security"],
  },
  {
    slug: "stripe",
    name: "Stripe Blog",
    siteUrl: "https://stripe.com/blog",
    rssUrl: "https://stripe.com/blog/feed.rss",
    authorityScore: 0.94,
    tags: ["backend", "web"],
  },
  {
    slug: "vercel",
    name: "Vercel Blog",
    siteUrl: "https://vercel.com/blog",
    rssUrl: "https://vercel.com/atom",
    authorityScore: 0.9,
    tags: ["vercel", "nextjs", "frontend", "web"],
  },
  {
    slug: "netflix",
    name: "Netflix TechBlog",
    siteUrl: "https://netflixtechblog.com",
    rssUrl: "https://netflixtechblog.com/feed",
    authorityScore: 0.96,
    tags: ["distributed-systems", "backend", "performance"],
  },
  {
    slug: "github",
    name: "GitHub Blog",
    siteUrl: "https://github.blog",
    rssUrl: "https://github.blog/feed/",
    authorityScore: 0.9,
    tags: ["github", "git", "open-source"],
  },
  {
    slug: "rust-blog",
    name: "Rust Blog",
    siteUrl: "https://blog.rust-lang.org",
    rssUrl: "https://blog.rust-lang.org/feed.xml",
    authorityScore: 0.93,
    tags: ["rust", "compilers", "open-source"],
  },
  {
    slug: "go-blog",
    name: "The Go Blog",
    siteUrl: "https://go.dev/blog",
    rssUrl: "https://go.dev/blog/feed.atom",
    authorityScore: 0.93,
    tags: ["go", "backend", "open-source"],
  },
  {
    slug: "kubernetes",
    name: "Kubernetes Blog",
    siteUrl: "https://kubernetes.io/blog",
    rssUrl: "https://kubernetes.io/feed.xml",
    authorityScore: 0.92,
    tags: ["kubernetes", "devops", "distributed-systems"],
  },
  {
    slug: "planet-postgres",
    name: "Planet PostgreSQL",
    siteUrl: "https://planet.postgresql.org",
    rssUrl: "https://planet.postgresql.org/rss20.xml",
    authorityScore: 0.88,
    tags: ["postgres", "sql", "databases"],
  },
  {
    slug: "nodejs",
    name: "Node.js Blog",
    siteUrl: "https://nodejs.org/blog",
    rssUrl: "https://nodejs.org/en/feed/blog.xml",
    authorityScore: 0.9,
    tags: ["node", "javascript", "backend"],
  },
  {
    slug: "deno",
    name: "Deno Blog",
    siteUrl: "https://deno.com/blog",
    rssUrl: "https://deno.com/feed",
    authorityScore: 0.82,
    tags: ["deno", "typescript", "javascript"],
  },
  {
    slug: "meta-engineering",
    name: "Engineering at Meta",
    siteUrl: "https://engineering.fb.com",
    rssUrl: "https://engineering.fb.com/feed/",
    authorityScore: 0.94,
    tags: ["distributed-systems", "backend", "performance"],
  },
  {
    slug: "uber-engineering",
    name: "Uber Engineering",
    siteUrl: "https://www.uber.com/blog/engineering",
    rssUrl: "https://www.uber.com/blog/engineering/rss/",
    authorityScore: 0.9,
    tags: ["distributed-systems", "backend"],
  },
  {
    slug: "spotify-engineering",
    name: "Spotify Engineering",
    siteUrl: "https://engineering.atspotify.com",
    rssUrl: "https://engineering.atspotify.com/feed/",
    authorityScore: 0.88,
    tags: ["backend", "distributed-systems"],
  },
  {
    slug: "discord-engineering",
    name: "Discord Engineering",
    siteUrl: "https://discord.com/blog",
    rssUrl: "https://discord.com/blog/rss.xml",
    authorityScore: 0.86,
    tags: ["backend", "performance"],
  },
  {
    slug: "prisma",
    name: "Prisma Blog",
    siteUrl: "https://www.prisma.io/blog",
    rssUrl: "https://www.prisma.io/blog/rss.xml",
    authorityScore: 0.8,
    tags: ["prisma", "typescript", "databases"],
  },
  {
    slug: "flyio",
    name: "Fly.io Blog",
    siteUrl: "https://fly.io/blog",
    rssUrl: "https://fly.io/blog/feed.xml",
    authorityScore: 0.84,
    tags: ["devops", "backend"],
  },
  {
    slug: "neon",
    name: "Neon Blog",
    siteUrl: "https://neon.tech/blog",
    rssUrl: "https://neon.tech/blog/rss.xml",
    authorityScore: 0.82,
    tags: ["postgres", "databases"],
  },
  {
    slug: "supabase",
    name: "Supabase Blog",
    siteUrl: "https://supabase.com/blog",
    rssUrl: "https://supabase.com/feed.xml",
    authorityScore: 0.82,
    tags: ["postgres", "databases", "web"],
  },
  {
    slug: "sentry",
    name: "Sentry Blog",
    siteUrl: "https://blog.sentry.io",
    rssUrl: "https://blog.sentry.io/feed.xml",
    authorityScore: 0.8,
    tags: ["performance", "backend"],
  },
  {
    slug: "grafana",
    name: "Grafana Blog",
    siteUrl: "https://grafana.com/blog",
    rssUrl: "https://grafana.com/blog/index.xml",
    authorityScore: 0.84,
    tags: ["devops", "performance"],
  },
  {
    slug: "hashicorp",
    name: "HashiCorp Blog",
    siteUrl: "https://www.hashicorp.com/blog",
    rssUrl: "https://www.hashicorp.com/blog/feed.xml",
    authorityScore: 0.86,
    tags: ["terraform", "devops"],
  },
  {
    slug: "docker",
    name: "Docker Blog",
    siteUrl: "https://www.docker.com/blog",
    rssUrl: "https://www.docker.com/feed/",
    authorityScore: 0.84,
    tags: ["docker", "devops"],
  },
  {
    slug: "aws-architecture",
    name: "AWS Architecture Blog",
    siteUrl: "https://aws.amazon.com/blogs/architecture",
    rssUrl: "https://aws.amazon.com/blogs/architecture/feed/",
    authorityScore: 0.9,
    tags: ["aws", "distributed-systems", "backend"],
  },
  {
    slug: "google-developers",
    name: "Google Developers Blog",
    siteUrl: "https://developers.googleblog.com",
    rssUrl: "https://developers.googleblog.com/atom.xml",
    authorityScore: 0.9,
    tags: ["web", "ai"],
  },
  {
    slug: "microsoft-devblogs",
    name: "Microsoft Developer Blogs",
    siteUrl: "https://devblogs.microsoft.com",
    rssUrl: "https://devblogs.microsoft.com/feed/",
    authorityScore: 0.88,
    tags: ["csharp", "azure", "web"],
  },
  {
    slug: "webkit",
    name: "WebKit Blog",
    siteUrl: "https://webkit.org/blog",
    rssUrl: "https://webkit.org/feed/",
    authorityScore: 0.9,
    tags: ["web", "performance", "css"],
  },
  {
    slug: "mozilla-hacks",
    name: "Mozilla Hacks",
    siteUrl: "https://hacks.mozilla.org",
    rssUrl: "https://hacks.mozilla.org/feed/",
    authorityScore: 0.88,
    tags: ["web", "javascript", "open-source"],
  },
  {
    slug: "chromium",
    name: "Chromium Blog",
    siteUrl: "https://blog.chromium.org",
    rssUrl: "https://blog.chromium.org/feeds/posts/default",
    authorityScore: 0.9,
    tags: ["web", "performance"],
  },
  {
    slug: "shopify-engineering",
    name: "Shopify Engineering",
    siteUrl: "https://shopify.engineering",
    rssUrl: "https://shopify.engineering/blog.atom",
    authorityScore: 0.88,
    tags: ["backend", "ruby", "performance"],
  },
  {
    slug: "slack-engineering",
    name: "Slack Engineering",
    siteUrl: "https://slack.engineering",
    rssUrl: "https://slack.engineering/feed",
    authorityScore: 0.86,
    tags: ["backend", "distributed-systems"],
  },
  {
    slug: "react-blog",
    name: "React Blog",
    siteUrl: "https://react.dev/blog",
    rssUrl: "https://react.dev/rss.xml",
    authorityScore: 0.95,
    tags: ["react", "javascript", "frontend"],
  },
  {
    slug: "nextjs-blog",
    name: "Next.js Blog",
    siteUrl: "https://nextjs.org/blog",
    rssUrl: "https://nextjs.org/feed.xml",
    authorityScore: 0.9,
    tags: ["nextjs", "react", "frontend"],
  },
  {
    slug: "swift",
    name: "Swift.org",
    siteUrl: "https://www.swift.org",
    rssUrl: "https://www.swift.org/atom.xml",
    authorityScore: 0.9,
    tags: ["swift", "open-source"],
  },
  {
    slug: "smashing",
    name: "Smashing Magazine",
    siteUrl: "https://www.smashingmagazine.com",
    rssUrl: "https://www.smashingmagazine.com/feed/",
    authorityScore: 0.78,
    tags: ["frontend", "css", "web"],
  },
  {
    slug: "css-tricks",
    name: "CSS-Tricks",
    siteUrl: "https://css-tricks.com",
    rssUrl: "https://css-tricks.com/feed/",
    authorityScore: 0.76,
    tags: ["css", "frontend", "web"],
  },
  {
    slug: "josh-comeau",
    name: "Josh Comeau",
    siteUrl: "https://www.joshwcomeau.com",
    rssUrl: "https://www.joshwcomeau.com/rss.xml",
    authorityScore: 0.8,
    tags: ["css", "react", "frontend"],
  },
  {
    slug: "kentcdodds",
    name: "Kent C. Dodds",
    siteUrl: "https://kentcdodds.com",
    rssUrl: "https://kentcdodds.com/blog/rss.xml",
    authorityScore: 0.78,
    tags: ["javascript", "react", "testing"],
  },
  {
    slug: "overreacted",
    name: "Overreacted",
    siteUrl: "https://overreacted.io",
    rssUrl: "https://overreacted.io/rss.xml",
    authorityScore: 0.84,
    tags: ["react", "javascript"],
  },
  {
    slug: "tkdodo",
    name: "TkDodo's blog",
    siteUrl: "https://tkdodo.eu/blog",
    rssUrl: "https://tkdodo.eu/blog/rss.xml",
    authorityScore: 0.8,
    tags: ["react", "javascript", "frontend"],
  },
  {
    slug: "2ality",
    name: "2ality",
    siteUrl: "https://2ality.com",
    rssUrl: "https://2ality.com/feeds/posts.atom",
    authorityScore: 0.76,
    tags: ["javascript", "typescript"],
  },
  {
    slug: "thenewstack",
    name: "The New Stack",
    siteUrl: "https://thenewstack.io",
    rssUrl: "https://thenewstack.io/feed/",
    authorityScore: 0.7,
    tags: ["devops", "kubernetes"],
  },
];
